//Faq list api
export const FAQ_LIST_PENDING = 'FAQ_LIST_PENDING'
export const FAQ_LIST_ERROR = 'FAQ_LIST_ERROR'
export const FAQ_LIST_SUCCESS = 'FAQ_LIST_SUCCESS'

//Privacy Policy Actions
export const PRIVACY_SERVICE_PENDING = 'PRIVACY_SERVICE_PENDING'
export const PRIVACY_SERVICE_ERROR = 'PRIVACY_SERVICE_ERROR'
export const PRIVACY_SERVICE_SUCCESS = 'PRIVACY_SERVICE_SUCCESS'

//Check Phone
export const CHECK_PHONE_PENDING = 'CHECK_PHONE_PENDING'
export const CHECK_PHONE_ERROR = 'CHECK_PHONE_ERROR'
export const CHECK_PHONE_SUCCESS = 'CHECK_PHONE_SUCCESS'

//Register
export const CREATE_COUNTRY_CODE = 'CREATE_COUNTRY_CODE'
export const CREATE_PHONE_NUMBER = 'CREATE_PHONE_NUMBER'
export const CREATE_PHONE_WITH_CODE = 'CREATE_PHONE_WITH_CODE'
export const CREATE_FIRST_NAME = 'CREATE_FIRST_NAME'
export const CREATE_LAST_NAME = 'CREATE_LAST_NAME'
export const CREATE_EMAIL_ADDRESS = 'CREATE_EMAIL_ADDRESS'
export const CREATE_LOGIN_PASSWORD = 'CREATE_LOGIN_PASSWORD'

export const REGISTER_PENDING = 'REGISTER_PENDING'
export const REGISTER_ERROR = 'REGISTER_ERROR'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'

//Login
export const LOGIN_PENDING = 'LOGIN_PENDING'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

//Profile
export const PROFILE_PENDING = 'PROFILE_PENDING'
export const PROFILE_ERROR = 'PROFILE_ERROR'
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS'
export const UPDATE_PROFILE_PICTURE = 'UPDATE_PROFILE_PICTURE'
 
//Notification list api
export const NOTIFICATION_LIST_PENDING = 'NOTIFICATION_LIST_PENDING'
export const NOTIFICATION_LIST_ERROR = 'NOTIFICATION_LIST_ERROR'
export const NOTIFICATION_LIST_SUCCESS = 'NOTIFICATION_LIST_SUCCESS'

//Wallet
export const ADD_WALLET_PENDING = 'ADD_WALLET_PENDING'
export const ADD_WALLET_ERROR = 'ADD_WALLET_ERROR'
export const ADD_WALLET_SUCCESS = 'ADD_WALLET_SUCCESS'

export const WALLET_PENDING = 'WALLET_PENDING'
export const WALLET_ERROR = 'WALLET_ERROR'
export const WALLET_SUCCESS = 'WALLET_SUCCESS'

//KYC
export const KYC_PENDING = 'KYC_PENDING'
export const KYC_ERROR = 'KYC_ERROR'
export const KYC_SUCCESS = 'KYC_SUCCESS'

//EARNINGS
export const EARNINGS_PENDING = 'EARNINGS_PENDING'
export const EARNINGS_ERROR = 'EARNINGS_ERROR'
export const EARNINGS_SUCCESS = 'EARNINGS_SUCCESS'

//Withdrawal
export const WITHDRAW_ACTION_PENDING = 'WITHDRAW_ACTION_PENDING'
export const WITHDRAW_ACTION_ERROR = 'WITHDRAW_ACTION_ERROR'
export const WITHDRAW_ACTION_SUCCESS = 'WITHDRAW_ACTION_SUCCESS'

//Forgot
export const CREATE_FORGOT_PHONE_WITH_CODE = 'CREATE_FORGOT_PHONE_WITH_CODE'

//Booking
export const UPDATE_VEHICLE_TYPE = 'UPDATE_VEHICLE_TYPE'

